dependencies:
  - pip
  - pip:
    - PyQt5
    - PyQt5.sip
    - numpy>1.16.0,<1.19.4
    - numba>=0.43.1
    - scipy=1.7.2
    - torch>=1.6
    - opencv-python-headless
    - natsort
    - tqdm
    - imagecodecs
    - tifffile
    - napari
    - scikit-learn>= 0.24.0
    - scikit-image>=0.14.2
    - matplotlib=3.4.3
    - pandas>=0.24.0
    - mrc>=0.1.5
